language: ruby
cache: bundler

rvm:
  - 2.3.1

before_install:
  - gem update --system

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake $TASKS

gemfile:
  - gemfiles/1.gemfile
  - gemfiles/rails_4.gemfile

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

env:
  global:
    - CC_TEST_REPORTER_ID=ebe8c89484407c039bfe9cd6c766dd415018d553f09c0acd606787f09bfd41a7
    - CF_RUN_PERM_SPECS=false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a47f3b0b8b0ddc96f09f
    on_success: change
    on_failure: always
    on_start: never

